---
- name : create httml
  hosts: all
  tasks:
  - name : Add html content
    copy :
      content: "This updated html"
      dest: /var/www/html/index.html
      
  - name: restart service
    service:
      name: httpd
      state: restarted 


