---
- name : Install httpd
  hosts: all
  tasks:
  - name : Install httpd
    yum: 
      name: httpd
      state: latest

  - name : Add html content
      copy :
      content: "This updated html"
      dest: /var/www/html/index.html

  - name : start the serive
    service:
      name : httpd
      state: started


